---
# yamllint disable rule:line-length
name: CI

# yamllint disable-line rule:truthy
on:
  - push
  - pull_request

jobs:
  run-tests:
    runs-on: ubuntu-20.04
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run CMake
      uses: lukka/run-cmake@v10
